version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_CACHE_HOST: redis:6379
    volumes:
      - wordpress_data:/var/www/html
      - ./metrics.php:/var/www/html/metrics.php
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  mysql-exporter:
    image: prom/mysqld-exporter
    command:
      - --config.my-cnf=/cfg/.my.cnf
      - --mysqld.address= 172.29.160.1:3306
    volumes:
      - "./.my.cnf:/cfg/.my.cnf"
    ports:
     - 9104:9104

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      
  redis_exporter:
    image: oliver006/redis_exporter:latest
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - "9121:9121"

volumes:
  wordpress_data:
  db_data:
