global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'wordpress'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'mysql_exporter'
    static_configs:
      - targets: 
          - 172.29.160.1:9104

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
